name: 'validate'

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']

permissions:
  contents: read

jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: 'NPM: install'
        run: npm ci
      - name: 'Validate Code Styling'
        run: npm run lint:prettier
      - name: 'Static Code Analysis'
        run: npm run lint:eslint

  test:
    needs:
      - lint
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            platform: 'linux'
            artifact_name: 'csv-to-xlsx-linux'
            artifact_path: 'bin/csv-to-xlsx-linux'
          - os: 'macos-latest'
            platform: 'macos'
            artifact_name: 'csv-to-xlsx-macos'
            artifact_path: 'bin/csv-to-xlsx-macos'
          - os: 'windows-latest'
            platform: 'win'
            artifact_name: 'csv-to-xlsx-win.exe'
            artifact_path: 'bin/csv-to-xlsx-win.exe'
    runs-on: ${{ matrix.os }}
    name: 'Node.js on ${{ matrix.os }}'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: 'NPM: install'
        run: npm ci
      - name: 'Build API and CLI version'
        run: npm run build:dist
      - name: 'Validate API'
        run: npm run test:api
      - name: 'Validate CLI'
        run: npm run test:cli
      - name: 'Build Binary version'
        run: npm run build:bin
      - name: 'Validate Binary'
        run: npm run test:bin -- -b ${{ matrix.artifact_path }}
      - name: 'Upload ${{ matrix.platform }} Binary'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
          retention-days: 7
          overwrite: 'true'
